spring:
  application:
    name: spring-ai-mcp-server
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springai-items-mcp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ymr1453443780
    hikari:
      pool-name: DataSourceHikariCP       # 连接池名字
      connection-timeout: 30000           # 等待连接池分配连接的最大时间（ms），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                     # 最小连接数
      maximum-pool-size: 20               # 最大连接数
      auto-commit: true                   # 自动提交
      idle-timeout: 600000                # 连接超时的最大时长（ms），超时则会被释放
      max-lifetime: 18000000              # 连接池的最大生命时长（ms），超时则会被释放
      connection-test-query: SELECT 1
  ai:
    mcp:
      server:
        name: spring-ai-mcp-server-sse
        version: 1.0.0
        type: async
        sse-message-endpoint: /mcp/message
        sse-endpoint: /sse
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
  mail:
    host: smtp.163.com
    port: 465
    username: yeling040629@163.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl.enable: true
          starttls.enable: true
          starttls.required: true

logging:
  level:
    root: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      update-strategy: not_empty
  mapper-locations: classpath*:/mapper/**/*.xml

