spring:
  application:
    name: spring-ai-mcp-server
  profiles:
    active: dev
  ai:
    mcp:
      server:
        name: spring-ai-mcp-server-sse
        version: 1.0.0
        type: async
        sse-message-endpoint: /mcp/message
        sse-endpoint: /sse
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
  mail:
    host: ${MAIL_HOST}  # 邮箱host
    port: ${MAIL_PORT}  # 邮箱port
    username: ${MAIL_USERNAME}  # 邮箱用户名
    password: ${MAIL_PASSWORD}  # 邮箱密码
    properties:
      mail:
        smtp:
          auth: true # 开启认证
          ssl.enable: true # 开启SSL
          starttls.enable: true # 开启TLS
          starttls.required: true # 必填

logging:
  level:
    root: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印sql
  global-config:
    db-config:
      id-type: assign_id  # 主键策略 - 默认自增
      update-strategy: not_empty  # 更新策略 - 默认非空
  mapper-locations: classpath*:/mapper/**/*.xml  # 扫描的mapper

