spring:
  application:
    name: spring-ai-mcp-server
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource  # 数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/springai-items-mcp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    hikari:
      pool-name: DataSourceHikariCP       # 连接池名字
      connection-timeout: 30000           # 等待连接池分配连接的最大时间（ms），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                     # 最小连接数
      maximum-pool-size: 20               # 最大连接数
      auto-commit: true                   # 自动提交
      idle-timeout: 600000                # 连接超时的最大时长（ms），超时则会被释放
      max-lifetime: 18000000              # 连接池的最大生命时长（ms），超时则会被释放
      connection-test-query: SELECT 1
  ai:
    mcp:
      server:
        name: spring-ai-mcp-server-sse
        version: 1.0.0
        type: async
        sse-message-endpoint: /mcp/message
        sse-endpoint: /sse
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
  mail:
    host: ${MAIL_HOST}  # 邮箱host
    port: ${MAIL_PORT}  # 邮箱port
    username: ${MAIL_USERNAME}  # 邮箱用户名
    password: ${MAIL_PASSWORD}  # 邮箱密码
    properties:
      mail:
        smtp:
          auth: true # 开启认证
          ssl.enable: true # 开启SSL
          starttls.enable: true # 开启TLS
          starttls.required: true # 必填

logging:
  level:
    root: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印sql
  global-config:
    db-config:
      id-type: assign_id  # 主键策略 - 默认自增
      update-strategy: not_empty  # 更新策略 - 默认非空
  mapper-locations: classpath*:/mapper/**/*.xml  # 扫描的mapper

