spring:
  application:
    name: spring-ai-mcp-server
  profiles:
    active: dev
  ai:
    mcp:
      server:
        name: spring-ai-mcp-server-sse
        version: 1.0.0
        type: async
        sse-message-endpoint: /mcp/message
        sse-endpoint: /sse
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true


logging:
  level:
    root: info
