spring:
  application:
    name: spring-ai-mcp-client
  profiles:
    active: dev
  ai:
    mcp:
      client:
        type: async
        sse:
          connections:
            server1:
              url: https://mcp.amap.com
              sse-endpoint: /sse?key=6876bf94ee5bf85d2d6de47d00532c58
            server2:
              url: http://localhost:9060
              sse-endpoint: /sse
        stdio:
          servers-configuration: classpath:mcp-servers.json
    vectorstore:
      redis:
        initialize-schema: true
        index-name: my-vector-index
        prefix: 'embedding:'
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}
    model:
      embedding: transformers
    embedding:
      transformer:
        tokenizer:
          uri: ${EMBEDDING_TOKENIZER_URL}
        onnx:
          model-uri: ${EMBEDDING_ONNX_MODEL_URL}
          model-output-name: token_embeddings

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: default
      password: ${REDIS_PASSWORD}

logging:
  level:
    root: info

internet:
  websearch:
    searxng:
      url: http://localhost:6080/search
      counts: 25

ok:
  http:
    read-timeout: 30
    write-timeout: 30