server:
  port: 9009

website:
  domain: ${WEBSITE_DOMAIN_DEV:http://localhost:5173,http://127.0.0.1:5173}

spring:
  ai:
    mcp:
      client:
        type: async
        sse:
          connections:
            server1:
              url: http://localhost:9060
              sse-endpoint: /sse
        stdio:
          servers-configuration: classpath:mcp-servers.json
    model:
      embedding: transformers
    embedding:
      transformer:
        tokenizer:
          uri: ${EMBEDDING_TOKENIZER_URL}
        onnx:
          model-uri: ${EMBEDDING_ONNX_MODEL_URL}
          model-output-name: token_embeddings

internet:
  websearch:
    searxng:
      url: http://localhost:6080/search
      counts: 25
