spring:
  application:
    name: spring-ai-mcp-client
  profiles:
    active: dev
  ai:
    vectorstore:
      redis:
        initialize-schema: true
        index-name: my-vector-index
        prefix: 'embedding:'

    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}

    qwen:
      api-key: ${QWEN_API_KEY}
      base-url: ${QWEN_BASE_URL}
      chat:
        options:
            model: ${QWEN_MODEL}
      audio:
        api-key: ${QWEN_AUDIO_API_KEY}
      video:
        api-key: ${QWEN_VIDEL_API_KEY}
    zhipuai:
      api-key: ${ZHIPU_API_KRY}
      base-url: ${ZHIPU_BASE_URL}
      chat:
        options:
          model: ${ZHIPU_MODEL}
          eval:
            model: ${ZHIPU_EVAL_MODEL}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: default
      password: ${REDIS_PASSWORD}
      timeout: 600000  # 连接超时时间（毫秒），增加到600秒
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 200000  # 获取连接的最大等待时间（毫秒）
      connect-timeout: 200000  # 连接超时（毫秒）
      client-type: jedis

logging:
  level:
    root: info

ok:
  http:
    read-timeout: 30
    write-timeout: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,observations # 暴露需要的端点
