spring:
  application:
    name: spring-ai-mcp-client
  profiles:
    active: dev
  ai:
    vectorstore:
      redis:
        initialize-schema: true
        index-name: my-vector-index
        prefix: 'embedding:'
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}
    model:
      embedding: transformers
    embedding:
      transformer:
        tokenizer:
          uri: file:\F:\AI\Model\onnx-output-folder\Qwen3-Embedding-0.6B\tokenizer.json
        onnx:
          model-uri: file:\F:\AI\Model\onnx-output-folder\Qwen3-Embedding-0.6B\model.onnx
          model-output-name: token_embeddings

  data:
    redis:
      host: redis-17826.c299.asia-northeast1-1.gce.redns.redis-cloud.com
      port: ${REDIS_PORT}
      username: default
      password: ${REDIS_PASSWORD}

logging:
  level:
    root: info