server:
  port: 9009

website:
  domain: ${WEBSITE_DOMAIN_DEV:http://localhost:5173,http://127.0.0.1:5173}

spring:
  ai:
    mcp:
      client:
        type: async
        sse:
          connections:
            server1:
              url: http://localhost:9060
              sse-endpoint: /sse
        stdio:
          servers-configuration: classpath:mcp-servers.json
    model:
      embedding: ollama
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: sam860/qwen3-embedding:0.6b-F16

internet:
  websearch:
    searxng:
      url: http://localhost:6080/search
      counts: 25
